"""Column definitions and normalization helpers for RAIS."""

from __future__ import annotations

CANONICAL_RENAMES = {
    "ano": "ano",
    "ano_declaracao": "ano",
    "municipio": "municipio",
    "municipio_codigo": "municipio",
    "mun_trab": "municipio_trabalho",
    "mun_trab_codigo": "municipio_trabalho",
    "municipio_trab_codigo": "municipio_trabalho",
    "municipio_trabalho": "municipio_trabalho",
    "uf": "uf",
    "cbo_ocupacao_2002": "cbo2002_ocupacao",
    "cbo_ocupacao_2002_codigo": "cbo2002_ocupacao",
    "cbo2002_ocupacao": "cbo2002_ocupacao",
    "cbo_2002": "cbo2002_ocupacao",
    "cbo_2002_ocupacao_codigo": "cbo2002_ocupacao",
    "cnae_2_0_classe": "classe",
    "cnae_2_0_classe_codigo": "classe",
    "cnae_2_0_subclasse": "subclasse",
    "cnae_2_0_subclasse_codigo": "subclasse",
    "cnae_95_classe": "classe_cnae_95",
    "cnae_95_classe_codigo": "classe_cnae_95",
    "grau_instrucao": "grau_de_instrucao",
    "grau_instrucao_apos_2005": "grau_de_instrucao",
    "escolaridade_apos_2005_codigo": "grau_de_instrucao",
    "qtd_hora_contr": "horas_contratuais",
    "qtd_horas_contr": "horas_contratuais",
    "horas_contratuais": "horas_contratuais",
    "idade": "idade",
    "raca_cor": "raca_cor",
    "raca_cor_codigo": "raca_cor",
    "raca_cor_apos_2005": "raca_cor",
    "sexo_trabalhador": "sexo",
    "sexo": "sexo",
    "sexo_codigo": "sexo",
    "nacionalidade": "nacionalidade",
    "nacionalidade_codigo": "nacionalidade",
    "natureza_juridica": "natureza_juridica",
    "natureza_juridica_codigo": "natureza_juridica",
    "tamanho_estabelecimento": "tamanho_estabelecimento",
    "tamanho_estabelecimento_codigo": "tamanho_estabelecimento",
    "tam_estab": "tamanho_estabelecimento",
    "tam_estab_jan": "tamanho_estabelecimento",
    "tipo_estab": "tipo_estabelecimento",
    "tipo_estabelecimento": "tipo_estabelecimento",
    "tipo_estabelecimento_codigo": "tipo_estabelecimento",
    "tipo_estab_1": "tipo_estabelecimento_1",
    "tipo_vinculo": "tipo_vinculo",
    "tipo_vinculo_codigo": "tipo_vinculo",
    "tipo_admissao": "tipo_admissao",
    "tipo_admissao_trabalhador_codigo": "tipo_admissao",
    "mes_admissao": "mes_admissao",
    "mes_admissao_codigo": "mes_admissao",
    "mes_desligamento": "mes_desligamento",
    "mes_desligamento_codigo": "mes_desligamento",
    "causa_desligamento": "causa_desligamento",
    "motivo_desligamento_codigo": "causa_desligamento",
    "vinculo_ativo_31_12": "vinculo_ativo_31_12",
    "vinculo_ativo_31_12_": "vinculo_ativo_31_12",
    "ind_vinculo_ativo_31_12_codigo": "vinculo_ativo_31_12",
    "tempo_emprego": "tempo_emprego",
    "vl_remun_media_nom": "remuneracao_media_nominal",
    "vl_remun_media_nominal": "remuneracao_media_nominal",
    "vl_rem_media_nom": "remuneracao_media_nominal",
    "remun_media_nom": "remuneracao_media_nominal",
    "vl_remun_media_sm": "remuneracao_media_sm",
    "vl_rem_media_sm": "remuneracao_media_sm",
    "vl_remun_dezembro_nom": "remuneracao_dezembro_nominal",
    "vl_remun_dezembro_nominal": "remuneracao_dezembro_nominal",
    "vl_rem_dezembro_nom": "remuneracao_dezembro_nominal",
    "remun_dezembro_nom": "remuneracao_dezembro_nominal",
    "vl_remun_dezembro_sm": "remuneracao_dezembro_sm",
    "vl_rem_dezembro_sm": "remuneracao_dezembro_sm",
    "salario_contratual": "salario_contratual",
    "salario_contr": "salario_contratual",
    "ind_simples": "indicador_simples",
    "ind_estabelecimento_participante_simples_codigo": "indicador_simples",
    "ind_cei_vinculado": "indicador_cei_vinculado",
    "ind_cei_vinculado_codigo": "indicador_cei_vinculado",
    "ind_portador_defic": "indicador_portador_deficiencia",
    "ind_portador_defic_codigo": "indicador_portador_deficiencia",
    "tipo_defic": "tipo_deficiencia",
    "tipo_deficiencia_codigo": "tipo_deficiencia",
    "ibge_subsetor": "ibge_subsetor",
    "ibge_subsetor_codigo": "ibge_subsetor",
    "ind_trabalho_intermitente_codigo": "indicador_trabalho_intermitente",
    "ind_trabalho_parcial_codigo": "indicador_trabalho_parcial",
    "ind_vinculo_abandonado_codigo": "indicador_vinculo_abandonado",
}

STANDARD_COLUMNS = [
    "ano",
    "uf",
    "municipio",
    "municipio_trabalho",
    "cbo2002_ocupacao",
    "classe",
    "subclasse",
    "classe_cnae_95",
    "grau_de_instrucao",
    "idade",
    "horas_contratuais",
    "raca_cor",
    "sexo",
    "nacionalidade",
    "natureza_juridica",
    "tamanho_estabelecimento",
    "tipo_estabelecimento",
    "tipo_estabelecimento_1",
    "tipo_vinculo",
    "tipo_admissao",
    "mes_admissao",
    "mes_desligamento",
    "causa_desligamento",
    "vinculo_ativo_31_12",
    "tempo_emprego",
    "remuneracao_media_nominal",
    "remuneracao_dezembro_nominal",
    "remuneracao_media_sm",
    "remuneracao_dezembro_sm",
    "salario_contratual",
    "indicador_simples",
    "indicador_cei_vinculado",
    "indicador_portador_deficiencia",
    "tipo_deficiencia",
    "ibge_subsetor",
    "indicador_trabalho_intermitente",
    "indicador_trabalho_parcial",
    "indicador_vinculo_abandonado",
    "source_year",
    "source_kind",
    "source_archive",
]

INTEGER_COLUMNS = ["idade", "horas_contratuais"]
DECIMAL_COLUMNS = [
    "tempo_emprego",
    "remuneracao_media_nominal",
    "remuneracao_dezembro_nominal",
    "remuneracao_media_sm",
    "remuneracao_dezembro_sm",
    "salario_contratual",
]
NUMERIC_COLUMNS = INTEGER_COLUMNS + DECIMAL_COLUMNS

CODE_COLUMNS = [
    "ano",
    "uf",
    "municipio",
    "municipio_trabalho",
    "cbo2002_ocupacao",
    "classe",
    "subclasse",
    "classe_cnae_95",
    "grau_de_instrucao",
    "raca_cor",
    "sexo",
    "nacionalidade",
    "natureza_juridica",
    "tamanho_estabelecimento",
    "tipo_estabelecimento",
    "tipo_estabelecimento_1",
    "tipo_vinculo",
    "tipo_admissao",
    "mes_admissao",
    "mes_desligamento",
    "causa_desligamento",
    "vinculo_ativo_31_12",
    "indicador_simples",
    "indicador_cei_vinculado",
    "indicador_portador_deficiencia",
    "tipo_deficiencia",
    "ibge_subsetor",
    "indicador_trabalho_intermitente",
    "indicador_trabalho_parcial",
    "indicador_vinculo_abandonado",
    "source_year",
    "source_kind",
    "source_archive",
]

BUILTIN_MEASURES = ("vinculos", "estoque_3112", "admitidos_ano", "desligados_ano")

UF_CODE_TO_GROUP_TOKEN = {
    **{uf: "NORTE" for uf in ("11", "12", "13", "14", "15", "16", "17")},
    **{uf: "NORDESTE" for uf in ("21", "22", "23", "24", "25", "26", "27", "28", "29")},
    **{uf: "MG_ES_RJ" for uf in ("31", "32", "33")},
    "35": "SP",
    **{uf: "SUL" for uf in ("41", "42", "43")},
    **{uf: "CENTRO_OESTE" for uf in ("50", "51", "52", "53")},
}
