"""Pdet package root."""

from pdet.common import (
    UF_ACRONYM_TO_CODE,
    UF_CODE_TO_ACRONYM,
    FTPContextManager,
    connect_ftp,
    ftp_nlst,
    ftp_download,
    select_period_range,
    run_tar_extract,
    remove_tree,
    find_files,
    sanitize_column_name,
    make_unique_columns,
    normalize_code_series,
    normalize_uf_series,
    coerce_numeric_columns,
    detect_delimiter,
    require_columns,
)

__all__ = [
    "UF_ACRONYM_TO_CODE",
    "UF_CODE_TO_ACRONYM",
    "FTPContextManager",
    "connect_ftp",
    "ftp_nlst",
    "ftp_download",
    "select_period_range",
    "run_tar_extract",
    "remove_tree",
    "find_files",
    "sanitize_column_name",
    "make_unique_columns",
    "normalize_code_series",
    "normalize_uf_series",
    "coerce_numeric_columns",
    "detect_delimiter",
    "require_columns",
]
